Feature/channel summation
project8/katydid pull request #187
Opened 2021-02-06 19:43 UTC by psurukuc

Not fully ready to merge. Need to confirm comments and such.

2021-02-07 16:11 UTC, psurukuc commented
Andrew has been implementing his time-dependent grid in Katydid and that depends on some of the updates on this branch. Plan to merge this branch to develop and then push those changes into feature/time-domain-ch-sum branch before requesting a PR.

2021-02-09 02:16 UTC, nsoblath requested changes
Very nice overall.  I didn't check all of the math, or anything, but for the most part the changes looked consistent with best practices and standards, both for C++ in general and Katydid specifically.  

Is there a test program for the channel aggregators?  If not, please add one that verifies that the processors are behaving as expected.

I have some comments that apply in many places, and I've tried to include individual comments where I've noticed individual instances, but some may have been missed.

* There are a number of places where spaces are missing between function arguments (calls and definitions) or where multiple variables are defined in one line.  Please add those spaces.
* Make sure to initialize variables where they're defined to avoid the possibility that they're used uninitialized.
* Standard practice in Katydid is to use unsigned ints for counting variables (like components or bins) if there's no chance of using a negative number.  In some cases I was pretty sure unsigned variables should be used.  In some cases I wasn't sure whether or not there was a possibility of a negative value.  Please check these and use unsigned in any case where negative values aren't expected.
* There were a few hard tab characters in at least one file.

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.cc
> +        fActiveRadius(0.0516),
Values should be initialized to things that are valid values for those variables, but will generally _not_ be useful in an analysis.  This way all users are made to explicitly specify things in their configs and not rely on default values that might get changed. So, e.g. numbers of things initialized to 0; maxes and mins to 0 and 1, respectively; wavelength to 0.

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.cc
> +        for(int i=0;i<channelCount;++i)
`int` --> `unsigned` and spaces between arguments

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.cc
> +        KTAggregatedFrequencySpectrumDataFFTW& newAggFreqData = fftwData.Of< KTAggregatedFrequencySpectrumDataFFTW >().SetNComponents(0);
`int` --> `unsigned` and spaces between arguments

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.cc
> +        int nTotalComponents = fftwData.GetNComponents(); // Get number of components
`int` --> `unsigned` and more spaces.
Either `if (true)` or `if( true )`, but be consistent.

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.hh
> +            MEMBERVARIABLE(int, PartialRingMultiplicity)
unsigned?

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.hh
> +            MEMBERVARIABLE(int, NRings);
unsigned

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.hh
> +            int DefineGrid(KTAggregatedFrequencySpectrumDataFFTW &newAggFreqData);
return value `unsigned`?

2021-02-09 02:16 UTC, nsoblath commented on Source/SpectrumAnalysis/KTChannelAggregator.hh
>  #include "KTData.hh"
This file has a bunch of tab characters in it.  Please convert all to 4 spaces

2021-02-11 19:22 UTC, psurukuc commented on Examples/ConfigFiles/GridPoints.txt
> +# Template for grid point file
Hi Noah, yes, there is no compelling reason to use text file. I work on chaging this to YAML file. Just so I unserstand correctly, you want that to be done in a new feature branch right after merging this one into develop ?

2021-02-11 19:24 UTC, nsoblath commented on Examples/ConfigFiles/GridPoints.txt
> +# Template for grid point file
That's right.  As I mentioned in one of the other comments, let's rename the relevant config parameters so they don't say "text" in their names, in anticipation of the change.  But let's not hold up the merge for this particular change.

2021-02-11 19:26 UTC, psurukuc commented on Source/IO/Conversions/KT2ROOT.cc
> +        for(int iZ=0;iZ<nZ;iZ++)
Done

2021-02-11 19:27 UTC, psurukuc commented on Source/IO/Conversions/KT2ROOT.cc
> +            aggfs.GetGridPoint(iComponents,xPos,yPos,zPos);
Done

2021-02-11 19:30 UTC, psurukuc commented on Source/IO/BasicROOTFileWriter/KTBasicROOTTypeWriterSpectrumAnalysis.cc
> +        std::vector<TGraph2D*> aggregatedGridGraphs = KT2ROOT::CreateGridGraphs(sumData,graphName);
Done

2021-02-11 19:50 UTC, psurukuc commented on Source/SpectrumAnalysis/KTAxialAggregator.cc
> +            fNRings= node->get_value< signed int >("n-rings", fNRings);
That is a mistake, thanks for catching.

2021-02-11 20:06 UTC, psurukuc commented
Hi Noah, thanks for very carefully going through the commits. I think I fixed all the suggestions expect for replacing YAML file with text file.

2021-02-11 20:18 UTC, psurukuc commented
Actually, please hold off on reviewing. I think I may have to make a few more changes. Also, I realized I haven't actually pushed all my changes to github yet.

2021-02-13 04:28 UTC, psurukuc commented
@nsoblath, thanks for the comments. I have implemented all the changes. There is a test program called TestChannelAggregator to test the ChannelAggregator and I modified it slightly to fit the new changes better.

2021-02-27 00:00 UTC, nsoblath approved these changes
This all looks good.  Thanks for all of the efforts on the this PR!

2021-02-27 00:01 UTC, merged