Feature/replace fftw complex
project8/katydid pull request #191
Opened 2021-04-21 18:28 UTC by MCFlowMace

2021-04-27 00:03 UTC, nsoblath requested changes
This is an impressive set of changes.  Clearly it cleans things up nicely.

There are several new dependencies on Eigen, including KTFractionalFFT and KTPhysicalArrayComplex (well, the latter I guess came in the previous PR).  We should either adopt Eigen as a standard dependency (which is the way it's headed anyhow) or modify the appropriate CMakeLists.txt files to only build/use the affected files if eigen is found.  I'm inclined to go with the former.

2021-04-27 14:36 UTC, MCFlowMace commented on Source/Data/Transform/KTFrequencySpectrumFFTW.cc
>      KTFrequencySpectrumFFTW::KTFrequencySpectrumFFTW(std::initializer_list<double> value, size_t nBins, double rangeMin, double rangeMax, bool arrayOrderIsFlipped) :
@nsoblath I do not think that this function does what it is supposed to do. Either that, or I do not understand its purpose. From the signature it looks like it should enable initialization like 
`KTFrequencySpectrumFFTW s({0.0, 1.0, 2.0, 3.0}, 2, 0.0, 1.0);`
and that should result in a 2 bin spectrum with s[0] = 0.0 + 1.0i, s[1] = 2.0 + 3.0i. If that is the case, it is not what the function does.

2021-04-27 14:55 UTC, MCFlowMace commented on Source/Data/Transform/KTFrequencySpectrumFFTW.cc
> +    //copy constructor, destructor and copy assignment operator
Done

2021-04-27 15:00 UTC, MCFlowMace commented
At the moment the optional `Katydid_USE_EIGEN` flag in the topmost CMakeLists.txt is just turned on by default. But can we make it optional still after the standard spectrum and timeseries objects now rely on it? What do you suggest to change other than switching the flag on by default?
Or maybe the question is actually, how is a standard dependency handled differently?

2021-04-27 19:02 UTC, psurukuc approved these changes

2021-04-27 19:03 UTC, psurukuc commented
Other than the ongoing disucssions about Eigen3 in CMakeLists, it all looks good to me.

2021-07-02 00:03 UTC, nsoblath approved these changes

2021-07-02 00:12 UTC, nsoblath commented
@MCFlowMace is there a minimum Eigen version?

2021-07-02 07:31 UTC, MCFlowMace commented
> @MCFlowMace is there a minimum Eigen version?

I developed with version 3.3.9, might also work with earlier versions of course but that's untested.

2021-07-02 16:35 UTC, merged